# Generated by Django 4.2.1 on 2023-05-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_url_delete_shortener'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
